In [6]:
# import necessary library
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [7]:
df = pd.read_csv('../Data/nisponno_records.csv')
df.shape

(100000, 18)

In [8]:
df.head()

id  nothi_master_id  nothi_part_no       type  nothi_onucched_id  \
0   1                1              1  potrojari                1.0   
1   2                3              5  potrojari                7.0   
2   3                3              6  potrojari               10.0   
3   4                7             10  potrojari               13.0   
4   5                9             12  potrojari               14.0   

   potrojari_id  nothi_office_id  office_id  unit_id  designation_id  \
0             0               11         11      333             817   
1             0               11         11      770            1810   
2             0               11         11      770            1810   
3             0               11         11      333             817   
4             0               11         11      770            1810   

   employee_id  upokarvogi  potrojari_internal_own  potrojari_internal_other  \
0           76           0                       0                         0   
1          478           0                       0                         0   
2          478           0                       0                         0   
3           76           0                       0                         0   
4          478           0                       0                         0   

   dak_srijito       operation_date              created             modified  
0            0  2016-02-10 00:00:00  2016-11-26 12:27:29  2016-11-26 12:27:29  
1            0  2016-02-13 00:00:00  2016-11-26 12:27:29  2016-11-26 12:27:29  
2            0  2016-02-13 00:00:00  2016-11-26 12:27:29  2016-11-26 12:27:29  
3            0  2016-11-16 00:00:00  2016-11-26 12:27:29  2016-11-26 12:27:29  
4            0  2016-02-14 00:00:00  2016-11-26 12:27:29  2016-11-26 12:27:29

In [27]:
# df.info(memory_usage="deep")
# df.unit_id.unique()
# df.unit_id.nunique()
df.upokarvogi.sum()


5

In [18]:
df.potrojari_internal_own.unique()
df.potrojari_internal_other.unique()
df.potrojari_internal_own.shape
df.potrojari_internal_other.shape
df.potrojari_internal_own.values

array([0])

array([0])

(100000,)

(100000,)

array([0, 0, 0, ..., 0, 0, 0])